import { CortexCrypto } from './crypto';
import { AIMemoryPayload } from './memory';

export type TransactionType = 'TRANSFER' | 'MEMORY_COMMIT' | 'COINBASE';

export interface ITransaction {
    id: string;
    type: TransactionType;
    sender: string;           // Address of sender (or 'COINBASE')
    senderPublicKey?: string; // Hex public key of sender
    recipient: string;        // Address of recipient (or 'CORTEX_BURN_ADDRESS' for burned memory fees)
    amount: number;           // Amount in CTX (e.g. 10.5 CTX)
    fee: number;              // Transaction fee paid to miner
    burnAmount: number;       // Deflationary amount destroyed permanently
    nonce: number;            // Monotonically increasing sequence number for replay protection
    timestamp: number;        // Epoch timestamp in milliseconds
    signature?: string;       // ECDSA DER signature in hex
    memoryPayload?: AIMemoryPayload; // Present if type === 'MEMORY_COMMIT'
}

export const CORTEX_BURN_ADDRESS = 'ctx100000000000000000000000000000000000000000000';

export class Transaction implements ITransaction {
    public id: string;
    public type: TransactionType;
    public sender: string;
    public senderPublicKey?: string;
    public recipient: string;
    public amount: number;
    public fee: number;
    public burnAmount: number;
    public nonce: number;
    public timestamp: number;
    public signature?: string;
    public memoryPayload?: AIMemoryPayload;

    constructor(data: {
        type: TransactionType;
        sender: string;
        senderPublicKey?: string;
        recipient: string;
        amount: number;
        fee?: number;
        burnAmount?: number;
        nonce?: number;
        timestamp?: number;
        signature?: string;
        memoryPayload?: AIMemoryPayload;
    }) {
        this.type = data.type;
        this.sender = data.sender;
        this.senderPublicKey = data.senderPublicKey;
        this.recipient = data.recipient;
        this.amount = Number(data.amount) || 0;
        this.fee = Number(data.fee) || 0;
        this.burnAmount = Number(data.burnAmount) || 0;
        this.nonce = data.nonce !== undefined ? data.nonce : 0;
        this.timestamp = data.timestamp || Date.now();
        this.signature = data.signature;
        this.memoryPayload = data.memoryPayload;

        this.id = this.calculateHash();
    }

    /**
     * Compute transaction hash (TxID) based on all immutable fields
     */
    public calculateHash(): string {
        const memHash = this.memoryPayload
            ? CortexCrypto.sha256(JSON.stringify(this.memoryPayload))
            : '';
            
        const raw = `${this.type}:${this.sender}:${this.recipient}:${this.amount}:${this.fee}:${this.burnAmount}:${this.nonce}:${this.timestamp}:${memHash}`;
        return CortexCrypto.sha256(raw);
    }

    /**
     * Sign transaction with sender's private key
     */
    public sign(privateKeyHex: string, publicKeyHex: string): void {
        if (this.type === 'COINBASE') {
            throw new Error('Coinbase transactions cannot be manually signed.');
        }

        this.senderPublicKey = publicKeyHex;
        const derivedAddr = CortexCrypto.deriveAddress(publicKeyHex);
        if (derivedAddr !== this.sender) {
            throw new Error(`Public key does not match sender address ${this.sender}`);
        }

        const hash = this.calculateHash();
        this.signature = CortexCrypto.sign(hash, privateKeyHex);
        this.id = hash;
    }

    /**
     * Verify transaction cryptographic signature and parameters
     */
    public isValid(): boolean {
        // Coinbase transactions are generated by miners and don't need signature
        if (this.type === 'COINBASE') {
            return this.sender === 'COINBASE' && this.amount > 0 && this.recipient.startsWith('ctx1');
        }

        if (!this.signature || !this.senderPublicKey) {
            return false;
        }

        // Verify address matches public key
        if (CortexCrypto.deriveAddress(this.senderPublicKey) !== this.sender) {
            return false;
        }

        if (this.amount < 0 || this.fee < 0 || this.burnAmount < 0) {
            return false;
        }

        // Verify ECDSA signature
        const hash = this.calculateHash();
        return CortexCrypto.verifySignature(hash, this.signature, this.senderPublicKey);
    }

    /**
     * Helper to create a Coinbase transaction for mining reward
     */
    static createCoinbase(minerAddress: string, rewardAmount: number, totalFees: number): Transaction {
        return new Transaction({
            type: 'COINBASE',
            sender: 'COINBASE',
            recipient: minerAddress,
            amount: rewardAmount + totalFees,
            fee: 0,
            burnAmount: 0,
            nonce: 0,
            timestamp: Date.now()
        });
    }

    /**
     * Helper to create a Memory Commit transaction with automatic 30% burn mechanism
     */
    static createMemoryCommit(
        agentAddress: string,
        agentPubKey: string,
        memoryPayload: AIMemoryPayload,
        networkFee: number,
        nonce: number
    ): Transaction {
        // 30% of memory gas is permanently burned, 70% goes to miner
        const burnPart = +(networkFee * 0.30).toFixed(6);
        const minerPart = +(networkFee * 0.70).toFixed(6);

        return new Transaction({
            type: 'MEMORY_COMMIT',
            sender: agentAddress,
            senderPublicKey: agentPubKey,
            recipient: CORTEX_BURN_ADDRESS,
            amount: 0,
            fee: minerPart,
            burnAmount: burnPart,
            nonce: nonce,
            memoryPayload: memoryPayload
        });
    }
}
